[package]
name = "ambientsensor"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
cortex-m-rtic = "1"
eeprom25aa02e48 = "0.2"
systick-monotonic = "1"
atomic-polyfill = "0.1"
log = { version = "0.4", features = ["release_max_level_warn"] }
stm32f0xx-hal = { version = "0.18", features = ["stm32f070xb", "rt"] }
w5500-dhcp = { version = "0.1.0", features = ["embedded-hal", "log"] }

[dependencies.bme280]
git = "https://github.com/newAM/bme280-rs.git"
rev = "2669ec67608522a56a066f0bf1596a81e72933d6"

[dependencies.mqtt]
package = "newam-mqtt"
git = "https://github.com/newAM/newam-mqtt.git"
rev = "d34c37d6fc7bf44a6ace4e4efffa35c95c235156"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = true
lto = false
opt-level = 3
overflow-checks = true

[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = true
lto = false
opt-level = 3
overflow-checks = true

[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = false
opt-level = 3
overflow-checks = true
