[package]
name = "ambientsensor"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2021"

[features]
release = []

[dependencies]
cortex-m = "~0.7.3"
cortex-m-rt = "~0.6.15"
embedded-hal = "~0.2.6"
cortex-m-rtic = "~0.5.8"
eeprom25aa02e48 = "~0.2"
dhcp = { path = "dhcp" }

[dependencies.w5500-hl]
version = "~0.4"
features = ["embedded-hal"]

[dependencies.stm32f0xx-hal]
git = "https://github.com/stm32-rs/stm32f0xx-hal.git"
rev = "fba9834b59fa7567ffd604afed2bcd8d07c4e904"
features = ["stm32f070xb", "rt"]

[dependencies.bme280]
git = "https://github.com/newAM/bme280-rs.git"
rev = "2669ec67608522a56a066f0bf1596a81e72933d6"

[profile.dev]
opt-level = "s"
debug = 2
debug-assertions = true

[workspace]
members = ["dhcp"]
