[package]
name = "ambientsensor"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"

[dependencies]
atomic-polyfill = "0.1"
bme280-multibus = "0.1.0"
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-rtic = "1"
eeprom25aa02e48 = "0.2"
embedded-hal = "0.2"
log = { version = "0.4", features = ["release_max_level_warn"] }
stm32f0xx-hal = { version = "0.18", features = ["stm32f070xb", "rt"] }
systick-monotonic = "1"
w5500-dhcp = { version = "0.1.0", features = ["embedded-hal", "log"] }

[dependencies.mqtt]
package = "newam-mqtt"
git = "https://github.com/newAM/newam-mqtt.git"
rev = "d34c37d6fc7bf44a6ace4e4efffa35c95c235156"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = true
lto = false
opt-level = 3
overflow-checks = true

[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = true
lto = false
opt-level = 3
overflow-checks = true

[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = false
opt-level = 3
overflow-checks = true
