[package]
name = "ambientsensor"
version = "0.1.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"

[features]
release = []

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
cortex-m-rtic = "0.6.0-rc.4"
eeprom25aa02e48 = "0.2"
dhcp = { path = "dhcp" }
systick-monotonic = "0.1.0-rc.2"

[dependencies.w5500-hl]
version = "0.7"
features = ["embedded-hal"]

[dependencies.stm32f0xx-hal]
version = "0.18"
features = ["stm32f070xb", "rt"]

[dependencies.bme280]
git = "https://github.com/newAM/bme280-rs.git"
rev = "2669ec67608522a56a066f0bf1596a81e72933d6"

[dependencies.mqtt]
package = "newam-mqtt"
git = "https://github.com/newAM/newam-mqtt.git"
rev = "d34c37d6fc7bf44a6ace4e4efffa35c95c235156"

[profile.dev]
opt-level = "s"
debug = 2
debug-assertions = true

[workspace]
members = ["dhcp"]
