[package]
name = "ambientsensor"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"

[features]
release = []

[dependencies]
cortex-m = "~0.7.1"
cortex-m-rt = "~0.6.13"
embedded-hal = "~0.2.4"
cortex-m-rtic = "~0.5.5"
eeprom25aa02e48 = "~0.2"
dhcp = { path = "dhcp" }

[dependencies.w5500-hl]
version = "~0.2"
features = ["embedded-hal"]

[dependencies.stm32f0xx-hal]
git = "https://github.com/stm32-rs/stm32f0xx-hal.git"
rev = "fba9834b59fa7567ffd604afed2bcd8d07c4e904"
features = ["stm32f070xb", "rt"] 

[profile.dev]
opt-level = "s"
debug = 2
debug-assertions = true

[workspace]
members = ["dhcp"]
