on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "13 3 * * 3"

name: CI

jobs:
  build:
    name: Debug Compile Check
    runs-on: ubuntu-latest
    env: {"RUSTFLAGS": "-D warnings"}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - run: cargo build --target thumbv6m-none-eabi
  
  build_release:
    name: Release Compile Check
    runs-on: ubuntu-latest
    env: {"RUSTFLAGS": "-D warnings"}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
      - run: cargo build --target thumbv6m-none-eabi --release

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      # not using clippy-check due to this issue:
      # https://github.com/actions-rs/clippy-check/issues/2
      - run: cargo clippy --all-features -- --deny warnings

  format_check:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check
